@_exported import PeekabooHumanInput

public typealias MouseMovementProfile = PeekabooHumanInput.MouseMovementProfile
public typealias HumanMouseProfileConfiguration = PeekabooHumanInput.HumanMouseProfileConfiguration
